#ifndef KV_CACHE_BLOCK_GATHER_TILING_KEY_H
#define KV_CACHE_BLOCK_GATHER_TILING_KEY_H

#include "ascendc/host_api/tiling/template_argument.h"

#define KV_CACHE_BLOCK_GATHER_FLOAT_MODE 1
#define KV_CACHE_BLOCK_GATHER_FLOAT16_MODE 2
#define KV_CACHE_BLOCK_GATHER_BF16_MODE 3

ASCENDC_TPL_ARGS_DECL(KvCacheBlockGather,
    ASCENDC_TPL_UINT_DECL(schMode, 2, ASCENDC_TPL_UI_LIST, KV_CACHE_BLOCK_GATHER_FLOAT_MODE,
        KV_CACHE_BLOCK_GATHER_FLOAT16_MODE, KV_CACHE_BLOCK_GATHER_BF16_MODE)
);

ASCENDC_TPL_SEL(
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_UINT_SEL(schMode, ASCENDC_TPL_UI_LIST, KV_CACHE_BLOCK_GATHER_FLOAT_MODE,
            KV_CACHE_BLOCK_GATHER_FLOAT16_MODE, KV_CACHE_BLOCK_GATHER_BF16_MODE)));

#endif
